name: md-to-pages
concurrency: md-to-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
          github-corners: https://github.com/pcafrica/hpc_for_data_science_2023-2024

      - name: Build slides HTML
        uses: docker://marpteam/marp-cli:latest
        with:
          args: --bespoke.progress --theme style/custom.css --html -I slides/ -o slides/
        env:
          MARP_USER: root:root

      - name: Build slides PDF
        uses: docker://marpteam/marp-cli:latest
        with:
          args: --bespoke.progress --theme style/custom.css --html -I slides/ -o slides/ --pdf --pdf-outlines
        env:
          MARP_USER: root:root

      - name: Build practical sessions HTML
        uses: docker://marpteam/marp-cli:latest
        with:
          args: --bespoke.progress --theme style/custom.css --html -I practical/ -o practical/
        env:
          MARP_USER: root:root

      - name: Build practical sessions PDF
        uses: docker://marpteam/marp-cli:latest
        with:
          args: --bespoke.progress --theme style/custom.css --html -I practical/ -o practical/ --pdf --pdf-outlines
        env:
          MARP_USER: root:root

      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
